### PR TITLE
1. Added support for retention policy configuration

### PR DESCRIPTION
**Pull request by sidgod**
2. RPs now working in create database, update database cases
3. Tested created, update of RPs

### CODE REVIEW

**Comment by sidgod** [comment]
I've now added the actual change in database resource, updated site documentation with description and examples for newly added section of retention policies. I've also added acceptance tests to make sure code is stable. Acceptance tests included create, update and delete for retention policies.

**Comment by sidgod** [comment]
@radeksimko Can you also add a reviewer to take this forward ?

**Comment by sidgod** [comment]
It's been 10+ days, can someone review my PL ?

**Comment by sidgod** [comment]
Any update on this @radeksimko ?

**Comment by sidgod** [comment]
@phinze Can you review this PL / assign someone else for the same please ?

**Comment by sidgod** [comment]
@radeksimko @phinze Guys any update on this ?

**Comment by sidgod** [comment]
Any update on this ?

**Comment by catsby** [comment]
Hey @sidgod ! I sincerely apologize for the long time this PR has gone with zero reply. 

The code looks good! The only question I have is regarding the ordering of retention policies. The code uses `TypeList`, which is ordered. If a user adds configuration in a particular order, Terraform will then expect the API to return the same order, otherwise it will present a diff. Is that correct behavior? 

If ordering is not relevant (the API may return them in any order) then the type should be `TypeSet`.
I can see policies going either way, depending on the context, which I admit I lack for InfluxDB. 

If they are ordered, then we're good to go, just please me know!

I apologize again for the long delay 😦

**Comment by sidgod** [comment]
Hi @catsby First off thanks for the review! InfluxDB preserves order while retrieve retention policy APIs. This will make sure we'll get same order as per user configuration. Since InfluxDB does maintain order of RPs in its API I think it would be good to replicate same behaviour in influxdb provider as well.

**Comment by catsby** [comment]
> Since InfluxDB does maintain order of RPs in its API I think it would be good to replicate same behaviour in influxdb provider as well.

Absolutely! I have no experience with InfluxDB myself so I wanted to confirm with you this was the case. 

I'll merge this now and cut a new release of the InfluxDB provider, we'll go ahead and jump to 1.0.0. 

Aside, this repository could use a maintainer, would you be interested perhaps? 

Thanks again!

**Comment by sidgod** [comment]
@catsby We are already using TF to provision Influx resources in production so I would love to be maintainer for this provider!

**Comment by catsby** [comment]
@sidgod excellent! We have a standard email that we send out to potential maintainers, simply asking they adhere to some community guidelines and such. If you could be so kind as to email me at clint @ hashicorp dot com then I'll send you the guides to read and we'll go from there. Thanks!

**Pull request merged**
