### PR TITLE
add optional shardGroupDuration in database configuration

### PR DESCRIPTION
**Pull request by kruegge**
Added support for optional shardGroupDuration in database. Was mentioned in https://github.com/terraform-providers/terraform-provider-influxdb/issues/2 but not implemented.

### CODE REVIEW

**Comment by sidgod** [comment]
@kruegge PR looks good, can you resolve the conflict and update the same so that I can go ahead and merge it ?

**Comment by kruegge** [comment]
@sidgod Sorry for late response. I solved the conflict.

**Comment by kruegge** [comment]
> @kruegge PR looks good, can you resolve the conflict and update the same so that I can go ahead and merge it ?

Sorry for late response, i solved the conflict.

**Comment by sidgod** [comment]
Hi @kruegge Ran tests, all are successful on CI. As a last change could you please update website docs to reflect new attribute added on influxdb database resource ? Website docs are available under website/docs/r path in repo. Once you update the docs, I can merge and initiate a release.

**Comment by sidgod** [comment]
PR Merged, working on getting new release out ...

**Comment by sidgod** [comment]
Queued up for release ...

**Comment by sidgod** [comment]
Released as v1.3.0 of InfluxDB provider

**Pull request merged**
