### PR TITLE
Hash and sensitive passwords

### PR DESCRIPTION
**Pull request by midN**
Added a hash function from similar mysql provider to hash passwords in a state file and mark then as sensitive to not have passwords outputted in a plaintext during plan/apply.

### CODE REVIEW

**Comment by midN** [comment]
@bflad @sidgod Can we get this merged ASAP?
It's unfortunate to see terraform apply/plan output a plaintext passwords, especially when we wish to get the terraform plan output printed somewhere for a wide audience like on Github PRs during CI/CD process.

**Comment by midN** [comment]
Is this repo still alive?

**Comment by sidgod** [comment]
I'm coming back from Vacation tomorrow, will trigger a build and release to prod!

**Comment by sidgod** [comment]
Released as part of 1.0.3 InfluxDB Provider

**Comment by midN** [comment]
@sidgod thank you!

**Pull request merged**
